version: '3'
services:
  web-server:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html
    depends_on:
      - video-service
      - user-service
      - content-service

  video-service:
    build:
      context: ./video-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./videos:/app/videos  

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./user-service:/app
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "user_service:app"]

  content-service:
    build:
      context: ./content-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./content-service:/app
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5002", "content_service:app"]