# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install Flask Flask-SQLAlchemy gunicorn

# Copy the index.html into the container
COPY index.html /app/templates/index.html

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Define environment variable
ENV NAME UserService

# Command to run on container start using Gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "user_service:app"]
