# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install Flask Flask-SQLAlchemy gunicorn

# Copy the index.html into the container
COPY index.html /app/index.html

# Make port 5002 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME VideoService

# Run Gunicorn with the configuration file
CMD ["gunicorn", "--config", "gunicorn_config.py", "video_service:app"]
